"""Generate the protocol bindings and golden fixture from deadcraft-protocol.toml.

    python protocol/generate.py           # write everything
    python protocol/generate.py --check   # exit 1 if any generated file is stale

Outputs (all committed, never hand-edited):
    csharp/src/Protocol.g.cs                          C# binding (plugin and tests compile it in)
    csharp/tests/Golden.g.cs                          golden values for the C# tests
    java/src/main/java/dev/deadcraft/protocol/*.java  Java binding
    java/src/test/java/dev/deadcraft/protocol/Golden.java
    golden/v1.bin                                     golden bytes, encoded here independently
"""
import struct
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SCHEMA = tomllib.loads((ROOT / "deadcraft-protocol.toml").read_text(encoding="utf-8"))
P = SCHEMA["protocol"]
STRUCTS = {s["name"]: s for s in SCHEMA["struct"]}
RINGS = SCHEMA.get("ring", [])
FLAGS = SCHEMA.get("flags", [])
ENUMS = SCHEMA.get("enum", [])
HEADER = "// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.\n"
JAVA_PKG = "dev.deadcraft.protocol"

SIZES = {"u32": 4, "i32": 4, "u64": 8, "f32": 4, "vec3": 12}


def type_size(t: str) -> int:
    if t.startswith("utf8["):
        return int(t[5:-1])
    return SIZES[t]


def validate() -> None:
    for s in STRUCTS.values():
        end = 0
        for f in s["fields"]:
            if f["offset"] < end:
                sys.exit(f"{s['name']}.{f['name']} overlaps the previous field")
            end = f["offset"] + type_size(f["type"])
        if end > s["size"]:
            sys.exit(f"{s['name']} fields run past its size")
    regions = [(s["offset"], s["size"], s["name"]) for s in STRUCTS.values() if "offset" in s]
    regions += [(r["offset"], r["capacity"] * STRUCTS[r["entry"]]["size"], r["name"]) for r in RINGS]
    regions += [(r["offset"], r["size"], r["name"]) for r in SCHEMA.get("reserved", [])]
    regions.sort()
    for (o1, s1, n1), (o2, _, n2) in zip(regions, regions[1:]):
        if o1 + s1 > o2:
            sys.exit(f"{n1} overlaps {n2}")
    last = regions[-1]
    if last[0] + last[1] > P["mapping_size"]:
        sys.exit(f"{last[2]} runs past mapping_size")


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def camel(name: str) -> str:
    p = pascal(name)
    return p[0].lower() + p[1:]


def golden_extent() -> int:
    ends = [s["offset"] + s["size"] for s in STRUCTS.values() if "offset" in s]
    ends += [r["offset"] + r["capacity"] * STRUCTS[r["entry"]]["size"] for r in RINGS]
    return max(ends)


# ---- golden values and the independent Python encoder -----------------------------------------

def load_values() -> dict:
    values = {}
    for line in (ROOT / "golden" / "v1.values").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, value = (part.strip() for part in line.split("=", 1))
        values[key] = value
    return values


def parse_value(t: str, raw: str):
    if t == "vec3":
        return tuple(float(v) for v in raw.split(","))
    if t == "f32":
        return float(raw)
    if t.startswith("utf8["):
        return raw
    return int(raw, 0)


def golden_structs(values: dict) -> list[tuple[str, int, dict]]:
    """(struct name, absolute offset, field values) for every struct instance in the golden file."""
    out = []
    for s in STRUCTS.values():
        if "offset" in s:
            fields = {f["name"]: parse_value(f["type"], values[f"{s['name']}.{f['name']}"]) for f in s["fields"]}
            out.append((s["name"], s["offset"], fields))
    for r in RINGS:
        entry = STRUCTS[r["entry"]]
        for i in range(r["capacity"]):
            prefix = f"{r['name']}[{i}]."
            if not any(k.startswith(prefix) for k in values):
                continue
            fields = {f["name"]: parse_value(f["type"], values[prefix + f["name"]]) for f in entry["fields"]}
            out.append((r["entry"], r["offset"] + i * entry["size"], fields))
    return out


def encode_golden(values: dict) -> bytes:
    buf = bytearray(golden_extent())
    for name, base, fields in golden_structs(values):
        for f in STRUCTS[name]["fields"]:
            at, t, v = base + f["offset"], f["type"], fields[f["name"]]
            if t == "vec3":
                struct.pack_into("<3f", buf, at, *v)
            elif t.startswith("utf8["):
                raw = v.encode("utf-8")
                assert len(raw) < type_size(t), f"{f['name']} too long"
                buf[at:at + len(raw)] = raw
            else:
                struct.pack_into("<" + {"u32": "I", "i32": "i", "u64": "Q", "f32": "f"}[t], buf, at, v)
    return bytes(buf)


# ---- C# -----------------------------------------------------------------------------------------

CS_TYPES = {"u32": "uint", "i32": "int", "u64": "ulong", "f32": "float", "vec3": "Vector3"}


def cs_type(t: str) -> str:
    return "string" if t.startswith("utf8[") else CS_TYPES[t]


def cs_read(t: str, at: str) -> str:
    if t == "vec3":
        return f"new Vector3(ReadSingle(s, {at}), ReadSingle(s, {at} + 4), ReadSingle(s, {at} + 8))"
    if t.startswith("utf8["):
        return f"ReadUtf8(s.Slice({at}, {type_size(t)}))"
    return {"u32": f"BinaryPrimitives.ReadUInt32LittleEndian(s.Slice({at}))",
            "i32": f"BinaryPrimitives.ReadInt32LittleEndian(s.Slice({at}))",
            "u64": f"BinaryPrimitives.ReadUInt64LittleEndian(s.Slice({at}))",
            "f32": f"ReadSingle(s, {at})"}[t]


def cs_write(t: str, at: str, v: str) -> str:
    if t == "vec3":
        return f"WriteSingle(s, {at}, {v}.X); WriteSingle(s, {at} + 4, {v}.Y); WriteSingle(s, {at} + 8, {v}.Z);"
    if t.startswith("utf8["):
        return f"WriteUtf8(s.Slice({at}, {type_size(t)}), {v});"
    return {"u32": f"BinaryPrimitives.WriteUInt32LittleEndian(s.Slice({at}), {v});",
            "i32": f"BinaryPrimitives.WriteInt32LittleEndian(s.Slice({at}), {v});",
            "u64": f"BinaryPrimitives.WriteUInt64LittleEndian(s.Slice({at}), {v});",
            "f32": f"WriteSingle(s, {at}, {v});"}[t]


def gen_csharp() -> str:
    o = [HEADER, "using System.Buffers.Binary;", "using System.Numerics;", "using System.Text;", "",
         "namespace Deadcraft.Protocol;", ""]
    o += ["/// <summary>Protocol constants. See protocol/deadcraft-protocol.toml.</summary>",
          "public static partial class Proto", "{",
          f"\tpublic const uint Magic = 0x{P['magic']:08X};",
          f"\tpublic const uint Version = {P['version']};",
          f"\tpublic const string MappingName = @\"{P['mapping_name']}\";",
          f"\tpublic const int MappingSize = {P['mapping_size']};",
          f"\tpublic const float UnitsPerBlock = {P['units_per_block']}f;", ""]
    for r in RINGS:
        n = pascal(r["name"]) if "_" in r["name"] else r["name"]
        o += [f"\tpublic const int {n}Offset = 0x{r['offset']:X};",
              f"\tpublic const int {n}Capacity = {r['capacity']};", ""]
    o += ["\t/// <summary>Deadlock (Source) units to Minecraft blocks: mc = (x, z, -y) / UnitsPerBlock.</summary>",
          "\tpublic static Vector3 ToMinecraft(Vector3 source) =>",
          "\t\tnew Vector3(source.X, source.Z, -source.Y) / UnitsPerBlock;", "",
          "\t/// <summary>Minecraft blocks to Deadlock (Source) units.</summary>",
          "\tpublic static Vector3 ToSource(Vector3 minecraft) =>",
          "\t\tnew Vector3(minecraft.X, -minecraft.Z, minecraft.Y) * UnitsPerBlock;", "",
          "\tinternal static float ReadSingle(ReadOnlySpan<byte> s, int at) => BinaryPrimitives.ReadSingleLittleEndian(s.Slice(at));",
          "\tinternal static void WriteSingle(Span<byte> s, int at, float v) => BinaryPrimitives.WriteSingleLittleEndian(s.Slice(at), v);",
          "\tinternal static string ReadUtf8(ReadOnlySpan<byte> s) { int n = s.IndexOf((byte)0); return Encoding.UTF8.GetString(n < 0 ? s : s[..n]); }",
          "\tinternal static void WriteUtf8(Span<byte> s, string v)",
          "\t{",
          "\t\ts.Clear();",
          "\t\tvar bytes = Encoding.UTF8.GetBytes(v);",
          "\t\tbytes.AsSpan(0, Math.Min(bytes.Length, s.Length - 1)).CopyTo(s);",
          "\t}",
          "}", ""]
    for fl in FLAGS:
        o += ["[Flags]", f"public enum {fl['name']} : uint", "{", "\tNone = 0,"]
        o += [f"\t{pascal(v['name'])} = 1u << {v['bit']}," for v in fl["values"]]
        o += ["}", ""]
    for en in ENUMS:
        o += [f"public enum {en['name']} : uint", "{"]
        o += [f"\t{pascal(v['name'])} = {v['value']}," for v in en["values"]]
        o += ["}", ""]
    for s in STRUCTS.values():
        o += [f"/// <summary>{s['doc']}</summary>", f"public struct {s['name']}", "{"]
        if "offset" in s:
            o.append(f"\tpublic const int Offset = 0x{s['offset']:X};")
        o.append(f"\tpublic const int Size = 0x{s['size']:X};")
        for f in s["fields"]:
            o.append(f"\tpublic const int {pascal(f['name'])}At = 0x{f['offset']:X};")
        o.append("")
        for f in s["fields"]:
            init = " = \"\";" if f["type"].startswith("utf8[") else ""
            doc = f" // {f['doc']}" if "doc" in f else ""
            o.append(f"\tpublic {cs_type(f['type'])} {pascal(f['name'])}{init}{';' if not init else ''}{doc}")
        o += ["", f"\tpublic {s['name']}() {{ }}", "",
              f"\t/// <summary>Decode from a span that starts at this struct.</summary>",
              f"\tpublic static {s['name']} Read(ReadOnlySpan<byte> s) => new()", "\t{"]
        for f in s["fields"]:
            o.append(f"\t\t{pascal(f['name'])} = " + cs_read(f["type"], f"{pascal(f['name'])}At").replace("ReadSingle(", "Proto.ReadSingle(").replace("ReadUtf8(", "Proto.ReadUtf8(") + ",")
        o += ["\t};", "", "\t/// <summary>Encode into a span that starts at this struct.</summary>",
              "\tpublic readonly void Write(Span<byte> s)", "\t{"]
        for f in s["fields"]:
            o.append("\t\t" + cs_write(f["type"], f"{pascal(f['name'])}At", pascal(f["name"])).replace("WriteSingle(", "Proto.WriteSingle(").replace("WriteUtf8(", "Proto.WriteUtf8("))
        o += ["\t}", "}", ""]
    return "\n".join(o)


def cs_literal(t: str, v) -> str:
    if t == "vec3":
        return f"new Vector3({v[0]}f, {v[1]}f, {v[2]}f)"
    if t == "f32":
        return f"{v}f"
    if t.startswith("utf8["):
        return f'"{v}"'
    return {"u32": f"{v}u", "i32": f"{v}", "u64": f"{v}ul"}[t]


def gen_csharp_golden(values: dict) -> str:
    o = [HEADER, "using System.Numerics;", "using Deadcraft.Protocol;", "", "namespace Deadcraft.Protocol.Tests;", "",
         "/// <summary>The values in protocol/golden/v1.values, as code.</summary>",
         "public static class Golden", "{",
         "\tpublic const int Extent = 0x%X;" % golden_extent(), ""]
    o.append("\t/// <summary>(absolute offset, struct) for every struct in the fixture.</summary>")
    o.append("\tpublic static readonly (int At, object Value)[] Structs =")
    o.append("\t[")
    for name, base, fields in golden_structs(values):
        inits = ", ".join(f"{pascal(f['name'])} = {cs_literal(f['type'], fields[f['name']])}" for f in STRUCTS[name]["fields"])
        o.append(f"\t\t(0x{base:X}, new {name} {{ {inits} }}),")
    o += ["\t];", "}", ""]
    return "\n".join(o)


# ---- Java ---------------------------------------------------------------------------------------

JAVA_TYPES = {"u32": "int", "i32": "int", "u64": "long", "f32": "float", "vec3": "Vec3"}


def java_type(t: str) -> str:
    return "String" if t.startswith("utf8[") else JAVA_TYPES[t]


def java_file(name: str, body: list[str], imports: tuple[str, ...] = ()) -> str:
    o = [HEADER.strip(), f"package {JAVA_PKG};", ""]
    if imports:
        o += [f"import {i};" for i in imports] + [""]
    return "\n".join(o + body) + "\n"


def gen_java() -> dict[str, str]:
    files = {}
    body = ["/** Protocol constants. See protocol/deadcraft-protocol.toml. */",
            "public final class Proto {",
            "\tprivate Proto() {}", "",
            f"\tpublic static final int MAGIC = 0x{P['magic']:08X};",
            f"\tpublic static final int VERSION = {P['version']};",
            f"\tpublic static final String MAPPING_NAME = \"{P['mapping_name'].replace(chr(92), chr(92) * 2)}\";",
            f"\tpublic static final int MAPPING_SIZE = {P['mapping_size']};",
            f"\tpublic static final float UNITS_PER_BLOCK = {P['units_per_block']}f;", ""]
    for r in RINGS:
        snake = "".join("_" + c if c.isupper() else c for c in r["name"]).lstrip("_").upper()
        body += [f"\tpublic static final int {snake}_OFFSET = 0x{r['offset']:X};",
                 f"\tpublic static final int {snake}_CAPACITY = {r['capacity']};", ""]
    body += ["\t/** Deadlock (Source) units to Minecraft blocks: mc = (x, z, -y) / UNITS_PER_BLOCK. */",
             "\tpublic static Vec3 toMinecraft(Vec3 s) {",
             "\t\treturn new Vec3(s.x() / UNITS_PER_BLOCK, s.z() / UNITS_PER_BLOCK, -s.y() / UNITS_PER_BLOCK);",
             "\t}", "",
             "\t/** Minecraft blocks to Deadlock (Source) units. */",
             "\tpublic static Vec3 toSource(Vec3 mc) {",
             "\t\treturn new Vec3(mc.x() * UNITS_PER_BLOCK, -mc.z() * UNITS_PER_BLOCK, mc.y() * UNITS_PER_BLOCK);",
             "\t}", "}"]
    files["Proto.java"] = java_file("Proto", body)
    files["Vec3.java"] = java_file("Vec3", ["/** Three floats, as the protocol stores them. */",
                                            "public record Vec3(float x, float y, float z) {",
                                            "\tpublic static final Vec3 ZERO = new Vec3(0, 0, 0);", "}"])
    for fl in FLAGS:
        body = [f"/** Bits of a protocol flags field. */", f"public final class {fl['name']} {{", f"\tprivate {fl['name']}() {{}}", ""]
        body += [f"\tpublic static final int {v['name'].upper()} = 1 << {v['bit']};" for v in fl["values"]]
        files[f"{fl['name']}.java"] = java_file(fl["name"], body + ["}"])
    for en in ENUMS:
        body = [f"/** Values of a protocol enum field. */", f"public final class {en['name']} {{", f"\tprivate {en['name']}() {{}}", ""]
        body += [f"\tpublic static final int {v['name'].upper()} = {v['value']};" for v in en["values"]]
        files[f"{en['name']}.java"] = java_file(en["name"], body + ["}"])
    for s in STRUCTS.values():
        n = s["name"]
        body = [f"/** {s['doc']} */", f"public final class {n} {{"]
        if "offset" in s:
            body.append(f"\tpublic static final int OFFSET = 0x{s['offset']:X};")
        body.append(f"\tpublic static final int SIZE = 0x{s['size']:X};")
        for f in s["fields"]:
            body.append(f"\tpublic static final int {f['name'].upper()}_AT = 0x{f['offset']:X};")
        body.append("")
        for f in s["fields"]:
            init = {"vec3": " = Vec3.ZERO", "utf8": ' = ""'}.get(f["type"].split("[")[0], "")
            unsigned = "  // unsigned" if f["type"] in ("u32", "u64") else ""
            doc = f"  // {f['doc']}" if "doc" in f else unsigned
            body.append(f"\tpublic {java_type(f['type'])} {camel(f['name'])}{init};{doc}")
        body += ["", "\t/** Decode from a little-endian buffer; {@code at} is where this struct starts. */",
                 f"\tpublic static {n} read(ByteBuffer b, int at) {{", f"\t\t{n} v = new {n}();"]
        for f in s["fields"]:
            t, field, pos = f["type"], camel(f["name"]), f"at + {f['name'].upper()}_AT"
            if t == "vec3":
                expr = f"new Vec3(b.getFloat({pos}), b.getFloat({pos} + 4), b.getFloat({pos} + 8))"
            elif t.startswith("utf8["):
                expr = f"Utf8.read(b, {pos}, {type_size(t)})"
            else:
                expr = {"u32": f"b.getInt({pos})", "i32": f"b.getInt({pos})", "u64": f"b.getLong({pos})", "f32": f"b.getFloat({pos})"}[t]
            body.append(f"\t\tv.{field} = {expr};")
        body += ["\t\treturn v;", "\t}", "", "\t/** Encode into a little-endian buffer; {@code at} is where this struct starts. */",
                 "\tpublic void write(ByteBuffer b, int at) {"]
        for f in s["fields"]:
            t, field, pos = f["type"], camel(f["name"]), f"at + {f['name'].upper()}_AT"
            if t == "vec3":
                body.append(f"\t\tb.putFloat({pos}, {field}.x()).putFloat({pos} + 4, {field}.y()).putFloat({pos} + 8, {field}.z());")
            elif t.startswith("utf8["):
                body.append(f"\t\tUtf8.write(b, {pos}, {type_size(t)}, {field});")
            else:
                body.append({"u32": f"\t\tb.putInt({pos}, {field});", "i32": f"\t\tb.putInt({pos}, {field});",
                             "u64": f"\t\tb.putLong({pos}, {field});", "f32": f"\t\tb.putFloat({pos}, {field});"}[t])
        body += ["\t}", "", "\t@Override", "\tpublic boolean equals(Object o) {",
                 f"\t\treturn o instanceof {n} v"]
        for f in s["fields"]:
            field = camel(f["name"])
            if f["type"] in ("vec3", ) or f["type"].startswith("utf8["):
                body.append(f"\t\t\t&& {field}.equals(v.{field})")
            elif f["type"] == "f32":
                body.append(f"\t\t\t&& Float.compare({field}, v.{field}) == 0")
            else:
                body.append(f"\t\t\t&& {field} == v.{field}")
        body[-1] += ";"
        body += ["\t}", "", "\t@Override", "\tpublic int hashCode() {",
                 "\t\treturn java.util.Objects.hash(" + ", ".join(camel(f["name"]) for f in s["fields"]) + ");", "\t}", "",
                 "\t@Override", "\tpublic String toString() {",
                 f"\t\treturn \"{n}[\" + " + " + \", \" + ".join(f'"{camel(f["name"])}=" + {camel(f["name"])}' for f in s["fields"]) + " + \"]\";",
                 "\t}", "}"]
        files[f"{n}.java"] = java_file(n, body, ("java.nio.ByteBuffer",))
    files["Utf8.java"] = java_file("Utf8", [
        "/** NUL-padded UTF-8 fixed-size strings. */",
        "final class Utf8 {",
        "\tprivate Utf8() {}", "",
        "\tstatic String read(ByteBuffer b, int at, int size) {",
        "\t\tint n = 0;",
        "\t\twhile (n < size && b.get(at + n) != 0) n++;",
        "\t\tbyte[] bytes = new byte[n];",
        "\t\tb.get(at, bytes);",
        "\t\treturn new String(bytes, StandardCharsets.UTF_8);",
        "\t}", "",
        "\tstatic void write(ByteBuffer b, int at, int size, String v) {",
        "\t\tbyte[] bytes = v.getBytes(StandardCharsets.UTF_8);",
        "\t\tint n = Math.min(bytes.length, size - 1);",
        "\t\tb.put(at, bytes, 0, n);",
        "\t\tfor (int i = n; i < size; i++) b.put(at + i, (byte) 0);",
        "\t}", "}"], ("java.nio.ByteBuffer", "java.nio.charset.StandardCharsets"))
    return files


def java_literal(t: str, v) -> str:
    if t == "vec3":
        return f"new Vec3({v[0]}f, {v[1]}f, {v[2]}f)"
    if t == "f32":
        return f"{v}f"
    if t.startswith("utf8["):
        return f'"{v}"'
    if t == "u64":
        return f"{v}L"
    if t == "u32" and v > 0x7FFFFFFF:
        return f"0x{v:08X}"
    return str(v)


def gen_java_golden(values: dict) -> str:
    o = [HEADER.strip(), f"package {JAVA_PKG};", "", "import java.util.List;", "",
         "/** The values in protocol/golden/v1.values, as code. */",
         "final class Golden {", "\tprivate Golden() {}", "",
         "\tstatic final int EXTENT = 0x%X;" % golden_extent(), "",
         "\trecord At(int offset, Object value) {}", "",
         "\tstatic List<At> structs() {", "\t\treturn List.of("]
    items = []
    for name, base, fields in golden_structs(values):
        sets = " ".join(f"v.{camel(f['name'])} = {java_literal(f['type'], fields[f['name']])};" for f in STRUCTS[name]["fields"])
        items.append(f"\t\t\tnew At(0x{base:X}, make(new {name}(), v -> {{ {sets} }}))")
    o.append(",\n".join(items))
    o += ["\t\t);", "\t}", "",
          "\tprivate static <T> T make(T v, java.util.function.Consumer<T> init) {",
          "\t\tinit.accept(v);", "\t\treturn v;", "\t}", "}", ""]
    return "\n".join(o)


# ---- main ---------------------------------------------------------------------------------------

def outputs() -> dict[Path, bytes]:
    validate()
    values = load_values()
    java_main = ROOT / "java" / "src" / "main" / "java" / "dev" / "deadcraft" / "protocol"
    out = {
        ROOT / "csharp" / "src" / "Protocol.g.cs": gen_csharp().encode(),
        ROOT / "csharp" / "tests" / "Golden.g.cs": gen_csharp_golden(values).encode(),
        ROOT / "java" / "src" / "test" / "java" / "dev" / "deadcraft" / "protocol" / "Golden.java": gen_java_golden(values).encode(),
        ROOT / "golden" / "v1.bin": encode_golden(values),
    }
    for name, text in gen_java().items():
        out[java_main / name] = text.encode()
    return out


def main() -> None:
    check = "--check" in sys.argv
    stale = []
    for path, data in outputs().items():
        # Text outputs are compared ignoring CRLF, which git may add on checkout.
        existing = path.read_bytes() if path.exists() else None
        if existing is not None and path.suffix != ".bin":
            existing = existing.replace(b"\r\n", b"\n")
        if existing == data:
            continue
        stale.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    for path in stale:
        print(("stale: " if check else "wrote: ") + str(path.relative_to(ROOT)))
    if check and stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
