// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.

using System.Buffers.Binary;
using System.Numerics;
using System.Text;

namespace Deadcraft.Protocol;

/// <summary>Protocol constants. See protocol/deadcraft-protocol.toml.</summary>
public static partial class Proto
{
	public const uint Magic = 0x54464344;
	public const uint Version = 3;
	public const string MappingName = @"Local\Deadcraft";
	public const int MappingSize = 262144;
	public const float UnitsPerBlock = 64.0f;

	public const int AbilityEventsOffset = 0x200;
	public const int AbilityEventsCapacity = 32;

	public const int CubesOffset = 0x1040;
	public const int CubesCapacity = 16384;

	/// <summary>Deadlock (Source) units to Minecraft blocks: mc = (x, z, -y) / UnitsPerBlock.</summary>
	public static Vector3 ToMinecraft(Vector3 source) =>
		new Vector3(source.X, source.Z, -source.Y) / UnitsPerBlock;

	/// <summary>Minecraft blocks to Deadlock (Source) units.</summary>
	public static Vector3 ToSource(Vector3 minecraft) =>
		new Vector3(minecraft.X, -minecraft.Z, minecraft.Y) * UnitsPerBlock;

	internal static float ReadSingle(ReadOnlySpan<byte> s, int at) => BinaryPrimitives.ReadSingleLittleEndian(s.Slice(at));
	internal static void WriteSingle(Span<byte> s, int at, float v) => BinaryPrimitives.WriteSingleLittleEndian(s.Slice(at), v);
	internal static string ReadUtf8(ReadOnlySpan<byte> s) { int n = s.IndexOf((byte)0); return Encoding.UTF8.GetString(n < 0 ? s : s[..n]); }
	internal static void WriteUtf8(Span<byte> s, string v)
	{
		s.Clear();
		var bytes = Encoding.UTF8.GetBytes(v);
		bytes.AsSpan(0, Math.Min(bytes.Length, s.Length - 1)).CopyTo(s);
	}
}

/// <summary>Three ints (protocol type ivec3).</summary>
public readonly record struct Int3(int X, int Y, int Z);

/// <summary>Three doubles (protocol type dvec3).</summary>
public readonly record struct Double3(double X, double Y, double Z);

[Flags]
public enum HeroFlags : uint
{
	None = 0,
	Present = 1u << 0,
	Alive = 1u << 1,
	OnGround = 1u << 2,
}

[Flags]
public enum McFlags : uint
{
	None = 0,
	Linked = 1u << 0,
}

public enum AbilityEventKind : uint
{
	Used = 1,
}

/// <summary>Identifies the mapping and shows which sides are alive.</summary>
public struct Header
{
	public const int Offset = 0x0;
	public const int Size = 0x40;
	public const int MagicAt = 0x0;
	public const int VersionAt = 0x4;
	public const int MappingSizeAt = 0x8;
	public const int UnitsPerBlockAt = 0xC;
	public const int DeadlockPidAt = 0x10;
	public const int MinecraftPidAt = 0x14;
	public const int DeadlockHeartbeatMsAt = 0x18;
	public const int MinecraftHeartbeatMsAt = 0x20;

	public uint Magic;
	public uint Version;
	public uint MappingSize;
	public float UnitsPerBlock;
	public uint DeadlockPid; // deadworks.exe process id
	public uint MinecraftPid;
	public ulong DeadlockHeartbeatMs; // GetTickCount64 at the plugin's last write
	public ulong MinecraftHeartbeatMs; // GetTickCount64 at the client's last write

	public Header() { }

	/// <summary>Decode from a span that starts at this struct.</summary>
	public static Header Read(ReadOnlySpan<byte> s) => new()
	{
		Magic = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(MagicAt)),
		Version = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(VersionAt)),
		MappingSize = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(MappingSizeAt)),
		UnitsPerBlock = Proto.ReadSingle(s, UnitsPerBlockAt),
		DeadlockPid = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(DeadlockPidAt)),
		MinecraftPid = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(MinecraftPidAt)),
		DeadlockHeartbeatMs = BinaryPrimitives.ReadUInt64LittleEndian(s.Slice(DeadlockHeartbeatMsAt)),
		MinecraftHeartbeatMs = BinaryPrimitives.ReadUInt64LittleEndian(s.Slice(MinecraftHeartbeatMsAt)),
	};

	/// <summary>Encode into a span that starts at this struct.</summary>
	public readonly void Write(Span<byte> s)
	{
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(MagicAt), Magic);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(VersionAt), Version);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(MappingSizeAt), MappingSize);
		Proto.WriteSingle(s, UnitsPerBlockAt, UnitsPerBlock);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(DeadlockPidAt), DeadlockPid);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(MinecraftPidAt), MinecraftPid);
		BinaryPrimitives.WriteUInt64LittleEndian(s.Slice(DeadlockHeartbeatMsAt), DeadlockHeartbeatMs);
		BinaryPrimitives.WriteUInt64LittleEndian(s.Slice(MinecraftHeartbeatMsAt), MinecraftHeartbeatMs);
	}
}

/// <summary>Deadlock -> Minecraft, written every server tick. Seqlock: seq is odd while the plugin writes.</summary>
public struct HeroState
{
	public const int Offset = 0x100;
	public const int Size = 0x80;
	public const int SeqAt = 0x0;
	public const int FlagsAt = 0x4;
	public const int TickAt = 0x8;
	public const int ServerTimeAt = 0x10;
	public const int HeroIdAt = 0x14;
	public const int PositionAt = 0x18;
	public const int VelocityAt = 0x24;
	public const int EyePositionAt = 0x30;
	public const int CameraAnglesAt = 0x3C;
	public const int StaminaAt = 0x48;
	public const int StaminaMaxAt = 0x4C;
	public const int HealthAt = 0x50;
	public const int HealthMaxAt = 0x54;
	public const int AbilityEventSerialAt = 0x58;
	public const int RecenterSerialAt = 0x5C;
	public const int RecenterDeltaAt = 0x60;

	public uint Seq;
	public uint Flags; // HeroFlags
	public ulong Tick; // Deadlock server tick count
	public float ServerTime; // seconds (CurTime)
	public uint HeroId; // Deadlock Heroes enum value
	public Vector3 Position; // feet, Source units
	public Vector3 Velocity; // Source units per second
	public Vector3 EyePosition; // Source units
	public Vector3 CameraAngles; // pitch, yaw, roll in degrees
	public float Stamina;
	public float StaminaMax;
	public int Health;
	public int HealthMax;
	public uint AbilityEventSerial; // serial of the newest AbilityEvent
	public uint RecenterSerial; // bumps each time the plugin recentres
	public Vector3 RecenterDelta; // Source units the hero and every collider moved in the latest recentre

	public HeroState() { }

	/// <summary>Decode from a span that starts at this struct.</summary>
	public static HeroState Read(ReadOnlySpan<byte> s) => new()
	{
		Seq = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(SeqAt)),
		Flags = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(FlagsAt)),
		Tick = BinaryPrimitives.ReadUInt64LittleEndian(s.Slice(TickAt)),
		ServerTime = Proto.ReadSingle(s, ServerTimeAt),
		HeroId = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(HeroIdAt)),
		Position = new Vector3(Proto.ReadSingle(s, PositionAt), Proto.ReadSingle(s, PositionAt + 4), Proto.ReadSingle(s, PositionAt + 8)),
		Velocity = new Vector3(Proto.ReadSingle(s, VelocityAt), Proto.ReadSingle(s, VelocityAt + 4), Proto.ReadSingle(s, VelocityAt + 8)),
		EyePosition = new Vector3(Proto.ReadSingle(s, EyePositionAt), Proto.ReadSingle(s, EyePositionAt + 4), Proto.ReadSingle(s, EyePositionAt + 8)),
		CameraAngles = new Vector3(Proto.ReadSingle(s, CameraAnglesAt), Proto.ReadSingle(s, CameraAnglesAt + 4), Proto.ReadSingle(s, CameraAnglesAt + 8)),
		Stamina = Proto.ReadSingle(s, StaminaAt),
		StaminaMax = Proto.ReadSingle(s, StaminaMaxAt),
		Health = BinaryPrimitives.ReadInt32LittleEndian(s.Slice(HealthAt)),
		HealthMax = BinaryPrimitives.ReadInt32LittleEndian(s.Slice(HealthMaxAt)),
		AbilityEventSerial = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(AbilityEventSerialAt)),
		RecenterSerial = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(RecenterSerialAt)),
		RecenterDelta = new Vector3(Proto.ReadSingle(s, RecenterDeltaAt), Proto.ReadSingle(s, RecenterDeltaAt + 4), Proto.ReadSingle(s, RecenterDeltaAt + 8)),
	};

	/// <summary>Encode into a span that starts at this struct.</summary>
	public readonly void Write(Span<byte> s)
	{
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(SeqAt), Seq);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(FlagsAt), Flags);
		BinaryPrimitives.WriteUInt64LittleEndian(s.Slice(TickAt), Tick);
		Proto.WriteSingle(s, ServerTimeAt, ServerTime);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(HeroIdAt), HeroId);
		Proto.WriteSingle(s, PositionAt, Position.X); Proto.WriteSingle(s, PositionAt + 4, Position.Y); Proto.WriteSingle(s, PositionAt + 8, Position.Z);
		Proto.WriteSingle(s, VelocityAt, Velocity.X); Proto.WriteSingle(s, VelocityAt + 4, Velocity.Y); Proto.WriteSingle(s, VelocityAt + 8, Velocity.Z);
		Proto.WriteSingle(s, EyePositionAt, EyePosition.X); Proto.WriteSingle(s, EyePositionAt + 4, EyePosition.Y); Proto.WriteSingle(s, EyePositionAt + 8, EyePosition.Z);
		Proto.WriteSingle(s, CameraAnglesAt, CameraAngles.X); Proto.WriteSingle(s, CameraAnglesAt + 4, CameraAngles.Y); Proto.WriteSingle(s, CameraAnglesAt + 8, CameraAngles.Z);
		Proto.WriteSingle(s, StaminaAt, Stamina);
		Proto.WriteSingle(s, StaminaMaxAt, StaminaMax);
		BinaryPrimitives.WriteInt32LittleEndian(s.Slice(HealthAt), Health);
		BinaryPrimitives.WriteInt32LittleEndian(s.Slice(HealthMaxAt), HealthMax);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(AbilityEventSerialAt), AbilityEventSerial);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(RecenterSerialAt), RecenterSerial);
		Proto.WriteSingle(s, RecenterDeltaAt, RecenterDelta.X); Proto.WriteSingle(s, RecenterDeltaAt + 4, RecenterDelta.Y); Proto.WriteSingle(s, RecenterDeltaAt + 8, RecenterDelta.Z);
	}
}

/// <summary>One ability or item use.</summary>
public struct AbilityEvent
{
	public const int Size = 0x40;
	public const int SerialAt = 0x0;
	public const int KindAt = 0x4;
	public const int TickAt = 0x8;
	public const int AbilityNameAt = 0x10;

	public uint Serial;
	public uint Kind; // AbilityEventKind
	public ulong Tick;
	public string AbilityName = ""; // e.g. citadel_ability_...

	public AbilityEvent() { }

	/// <summary>Decode from a span that starts at this struct.</summary>
	public static AbilityEvent Read(ReadOnlySpan<byte> s) => new()
	{
		Serial = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(SerialAt)),
		Kind = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(KindAt)),
		Tick = BinaryPrimitives.ReadUInt64LittleEndian(s.Slice(TickAt)),
		AbilityName = Proto.ReadUtf8(s.Slice(AbilityNameAt, 48)),
	};

	/// <summary>Encode into a span that starts at this struct.</summary>
	public readonly void Write(Span<byte> s)
	{
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(SerialAt), Serial);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(KindAt), Kind);
		BinaryPrimitives.WriteUInt64LittleEndian(s.Slice(TickAt), Tick);
		Proto.WriteUtf8(s.Slice(AbilityNameAt, 48), AbilityName);
	}
}

/// <summary>Minecraft -> Deadlock. Seqlock: seq is odd while the client writes; the seqlock also covers the cube_count entries of Cubes. The client rewrites both only when the set changes (generation bumps).</summary>
public struct McState
{
	public const int Offset = 0x1000;
	public const int Size = 0x40;
	public const int SeqAt = 0x0;
	public const int FlagsAt = 0x4;
	public const int GenerationAt = 0x8;
	public const int CubeCountAt = 0xC;
	public const int BaseAt = 0x10;
	public const int FrameOffsetAt = 0x20;

	public uint Seq;
	public uint Flags; // McFlags
	public uint Generation; // bumps whenever the cube set or the offset changes
	public uint CubeCount;
	public Int3 Base; // Minecraft block coordinates that cube positions are relative to
	public Double3 FrameOffset; // added to Minecraft block coordinates gives hero-frame blocks: source = to_source(mc + offset)

	public McState() { }

	/// <summary>Decode from a span that starts at this struct.</summary>
	public static McState Read(ReadOnlySpan<byte> s) => new()
	{
		Seq = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(SeqAt)),
		Flags = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(FlagsAt)),
		Generation = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(GenerationAt)),
		CubeCount = BinaryPrimitives.ReadUInt32LittleEndian(s.Slice(CubeCountAt)),
		Base = new Int3(BinaryPrimitives.ReadInt32LittleEndian(s.Slice(BaseAt + 0)), BinaryPrimitives.ReadInt32LittleEndian(s.Slice(BaseAt + 4)), BinaryPrimitives.ReadInt32LittleEndian(s.Slice(BaseAt + 8))),
		FrameOffset = new Double3(BinaryPrimitives.ReadDoubleLittleEndian(s.Slice(FrameOffsetAt + 0)), BinaryPrimitives.ReadDoubleLittleEndian(s.Slice(FrameOffsetAt + 8)), BinaryPrimitives.ReadDoubleLittleEndian(s.Slice(FrameOffsetAt + 16))),
	};

	/// <summary>Encode into a span that starts at this struct.</summary>
	public readonly void Write(Span<byte> s)
	{
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(SeqAt), Seq);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(FlagsAt), Flags);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(GenerationAt), Generation);
		BinaryPrimitives.WriteUInt32LittleEndian(s.Slice(CubeCountAt), CubeCount);
		BinaryPrimitives.WriteInt32LittleEndian(s.Slice(BaseAt + 0), Base.X); BinaryPrimitives.WriteInt32LittleEndian(s.Slice(BaseAt + 4), Base.Y); BinaryPrimitives.WriteInt32LittleEndian(s.Slice(BaseAt + 8), Base.Z);
		BinaryPrimitives.WriteDoubleLittleEndian(s.Slice(FrameOffsetAt + 0), FrameOffset.X); BinaryPrimitives.WriteDoubleLittleEndian(s.Slice(FrameOffsetAt + 8), FrameOffset.Y); BinaryPrimitives.WriteDoubleLittleEndian(s.Slice(FrameOffsetAt + 16), FrameOffset.Z);
	}
}

/// <summary>An axis-aligned cube of solid space. Position is its minimum corner in half blocks relative to McState.base (times 2); edge is its size in half blocks (1, 2, 4, 8 or 16) and position is a multiple of it.</summary>
public struct Cube
{
	public const int Size = 0x8;
	public const int XAt = 0x0;
	public const int YAt = 0x2;
	public const int ZAt = 0x4;
	public const int EdgeAt = 0x6;

	public short X;
	public short Y;
	public short Z;
	public byte Edge; // edge length in half blocks

	public Cube() { }

	/// <summary>Decode from a span that starts at this struct.</summary>
	public static Cube Read(ReadOnlySpan<byte> s) => new()
	{
		X = BinaryPrimitives.ReadInt16LittleEndian(s.Slice(XAt)),
		Y = BinaryPrimitives.ReadInt16LittleEndian(s.Slice(YAt)),
		Z = BinaryPrimitives.ReadInt16LittleEndian(s.Slice(ZAt)),
		Edge = s[EdgeAt],
	};

	/// <summary>Encode into a span that starts at this struct.</summary>
	public readonly void Write(Span<byte> s)
	{
		BinaryPrimitives.WriteInt16LittleEndian(s.Slice(XAt), X);
		BinaryPrimitives.WriteInt16LittleEndian(s.Slice(YAt), Y);
		BinaryPrimitives.WriteInt16LittleEndian(s.Slice(ZAt), Z);
		s[EdgeAt] = Edge;
	}
}
