// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;

/** One ability or item use. */
public final class AbilityEvent {
	public static final int SIZE = 0x40;
	public static final int SERIAL_AT = 0x0;
	public static final int KIND_AT = 0x4;
	public static final int TICK_AT = 0x8;
	public static final int ABILITY_NAME_AT = 0x10;

	public int serial;  // unsigned
	public int kind;  // AbilityEventKind
	public long tick;  // unsigned
	public String abilityName = "";  // e.g. citadel_ability_...

	/** Decode from a little-endian buffer; {@code at} is where this struct starts. */
	public static AbilityEvent read(ByteBuffer b, int at) {
		AbilityEvent v = new AbilityEvent();
		v.serial = b.getInt(at + SERIAL_AT);
		v.kind = b.getInt(at + KIND_AT);
		v.tick = b.getLong(at + TICK_AT);
		v.abilityName = Utf8.read(b, at + ABILITY_NAME_AT, 48);
		return v;
	}

	/** Encode into a little-endian buffer; {@code at} is where this struct starts. */
	public void write(ByteBuffer b, int at) {
		b.putInt(at + SERIAL_AT, serial);
		b.putInt(at + KIND_AT, kind);
		b.putLong(at + TICK_AT, tick);
		Utf8.write(b, at + ABILITY_NAME_AT, 48, abilityName);
	}

	@Override
	public boolean equals(Object o) {
		return o instanceof AbilityEvent v
			&& serial == v.serial
			&& kind == v.kind
			&& tick == v.tick
			&& abilityName.equals(v.abilityName);
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(serial, kind, tick, abilityName);
	}

	@Override
	public String toString() {
		return "AbilityEvent[" + "serial=" + serial + ", " + "kind=" + kind + ", " + "tick=" + tick + ", " + "abilityName=" + abilityName + "]";
	}
}
