// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Values of a protocol enum field. */
public final class AbilityEventKind {
	private AbilityEventKind() {}

	public static final int USED = 1;
}
