// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;

/** An axis-aligned cube of solid space. Position is its minimum corner in half blocks relative to McState.base (times 2); edge is its size in half blocks (1, 2, 4, 8 or 16) and position is a multiple of it. */
public final class Cube {
	public static final int SIZE = 0x8;
	public static final int X_AT = 0x0;
	public static final int Y_AT = 0x2;
	public static final int Z_AT = 0x4;
	public static final int EDGE_AT = 0x6;

	public short x;
	public short y;
	public short z;
	public int edge;  // edge length in half blocks

	/** Decode from a little-endian buffer; {@code at} is where this struct starts. */
	public static Cube read(ByteBuffer b, int at) {
		Cube v = new Cube();
		v.x = b.getShort(at + X_AT);
		v.y = b.getShort(at + Y_AT);
		v.z = b.getShort(at + Z_AT);
		v.edge = Byte.toUnsignedInt(b.get(at + EDGE_AT));
		return v;
	}

	/** Encode into a little-endian buffer; {@code at} is where this struct starts. */
	public void write(ByteBuffer b, int at) {
		b.putShort(at + X_AT, x);
		b.putShort(at + Y_AT, y);
		b.putShort(at + Z_AT, z);
		b.put(at + EDGE_AT, (byte) edge);
	}

	@Override
	public boolean equals(Object o) {
		return o instanceof Cube v
			&& x == v.x
			&& y == v.y
			&& z == v.z
			&& edge == v.edge;
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(x, y, z, edge);
	}

	@Override
	public String toString() {
		return "Cube[" + "x=" + x + ", " + "y=" + y + ", " + "z=" + z + ", " + "edge=" + edge + "]";
	}
}
