// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Three doubles (protocol type dvec3). */
public record Double3(double x, double y, double z) {
	public static final Double3 ZERO = new Double3(0, 0, 0);
}
