// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;

/** Identifies the mapping and shows which sides are alive. */
public final class Header {
	public static final int OFFSET = 0x0;
	public static final int SIZE = 0x40;
	public static final int MAGIC_AT = 0x0;
	public static final int VERSION_AT = 0x4;
	public static final int MAPPING_SIZE_AT = 0x8;
	public static final int UNITS_PER_BLOCK_AT = 0xC;
	public static final int DEADLOCK_PID_AT = 0x10;
	public static final int MINECRAFT_PID_AT = 0x14;
	public static final int DEADLOCK_HEARTBEAT_MS_AT = 0x18;
	public static final int MINECRAFT_HEARTBEAT_MS_AT = 0x20;

	public int magic;  // unsigned
	public int version;  // unsigned
	public int mappingSize;  // unsigned
	public float unitsPerBlock;
	public int deadlockPid;  // deadworks.exe process id
	public int minecraftPid;  // unsigned
	public long deadlockHeartbeatMs;  // GetTickCount64 at the plugin's last write
	public long minecraftHeartbeatMs;  // GetTickCount64 at the client's last write

	/** Decode from a little-endian buffer; {@code at} is where this struct starts. */
	public static Header read(ByteBuffer b, int at) {
		Header v = new Header();
		v.magic = b.getInt(at + MAGIC_AT);
		v.version = b.getInt(at + VERSION_AT);
		v.mappingSize = b.getInt(at + MAPPING_SIZE_AT);
		v.unitsPerBlock = b.getFloat(at + UNITS_PER_BLOCK_AT);
		v.deadlockPid = b.getInt(at + DEADLOCK_PID_AT);
		v.minecraftPid = b.getInt(at + MINECRAFT_PID_AT);
		v.deadlockHeartbeatMs = b.getLong(at + DEADLOCK_HEARTBEAT_MS_AT);
		v.minecraftHeartbeatMs = b.getLong(at + MINECRAFT_HEARTBEAT_MS_AT);
		return v;
	}

	/** Encode into a little-endian buffer; {@code at} is where this struct starts. */
	public void write(ByteBuffer b, int at) {
		b.putInt(at + MAGIC_AT, magic);
		b.putInt(at + VERSION_AT, version);
		b.putInt(at + MAPPING_SIZE_AT, mappingSize);
		b.putFloat(at + UNITS_PER_BLOCK_AT, unitsPerBlock);
		b.putInt(at + DEADLOCK_PID_AT, deadlockPid);
		b.putInt(at + MINECRAFT_PID_AT, minecraftPid);
		b.putLong(at + DEADLOCK_HEARTBEAT_MS_AT, deadlockHeartbeatMs);
		b.putLong(at + MINECRAFT_HEARTBEAT_MS_AT, minecraftHeartbeatMs);
	}

	@Override
	public boolean equals(Object o) {
		return o instanceof Header v
			&& magic == v.magic
			&& version == v.version
			&& mappingSize == v.mappingSize
			&& Float.compare(unitsPerBlock, v.unitsPerBlock) == 0
			&& deadlockPid == v.deadlockPid
			&& minecraftPid == v.minecraftPid
			&& deadlockHeartbeatMs == v.deadlockHeartbeatMs
			&& minecraftHeartbeatMs == v.minecraftHeartbeatMs;
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(magic, version, mappingSize, unitsPerBlock, deadlockPid, minecraftPid, deadlockHeartbeatMs, minecraftHeartbeatMs);
	}

	@Override
	public String toString() {
		return "Header[" + "magic=" + magic + ", " + "version=" + version + ", " + "mappingSize=" + mappingSize + ", " + "unitsPerBlock=" + unitsPerBlock + ", " + "deadlockPid=" + deadlockPid + ", " + "minecraftPid=" + minecraftPid + ", " + "deadlockHeartbeatMs=" + deadlockHeartbeatMs + ", " + "minecraftHeartbeatMs=" + minecraftHeartbeatMs + "]";
	}
}
