// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Bits of a protocol flags field. */
public final class HeroFlags {
	private HeroFlags() {}

	public static final int PRESENT = 1 << 0;
	public static final int ALIVE = 1 << 1;
	public static final int ON_GROUND = 1 << 2;
}
