// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;

/** Deadlock -> Minecraft, written every server tick. Seqlock: seq is odd while the plugin writes. */
public final class HeroState {
	public static final int OFFSET = 0x100;
	public static final int SIZE = 0x100;
	public static final int SEQ_AT = 0x0;
	public static final int FLAGS_AT = 0x4;
	public static final int TICK_AT = 0x8;
	public static final int SERVER_TIME_AT = 0x10;
	public static final int HERO_ID_AT = 0x14;
	public static final int POSITION_AT = 0x18;
	public static final int VELOCITY_AT = 0x24;
	public static final int EYE_POSITION_AT = 0x30;
	public static final int CAMERA_ANGLES_AT = 0x3C;
	public static final int STAMINA_AT = 0x48;
	public static final int STAMINA_MAX_AT = 0x4C;
	public static final int HEALTH_AT = 0x50;
	public static final int HEALTH_MAX_AT = 0x54;
	public static final int ABILITY_EVENT_SERIAL_AT = 0x58;
	public static final int RECENTER_SERIAL_AT = 0x5C;
	public static final int RECENTER_DELTA_AT = 0x60;
	public static final int HULL_HEIGHT_AT = 0x6C;
	public static final int ENTITY_FLAGS_AT = 0x70;
	public static final int BUTTONS_AT = 0x78;
	public static final int SHOT_SERIAL_AT = 0x80;

	public int seq;  // unsigned
	public int flags;  // HeroFlags
	public long tick;  // Deadlock server tick count
	public float serverTime;  // seconds (CurTime)
	public int heroId;  // Deadlock Heroes enum value
	public Vec3 position = Vec3.ZERO;  // feet, Source units
	public Vec3 velocity = Vec3.ZERO;  // Source units per second
	public Vec3 eyePosition = Vec3.ZERO;  // Source units
	public Vec3 cameraAngles = Vec3.ZERO;  // pitch, yaw, roll in degrees
	public float stamina;
	public float staminaMax;
	public int health;
	public int healthMax;
	public int abilityEventSerial;  // serial of the newest AbilityEvent
	public int recenterSerial;  // bumps each time the plugin recentres
	public Vec3 recenterDelta = Vec3.ZERO;  // Source units the hero and every collider moved in the latest recentre
	public float hullHeight;  // collision box height, Source units (shrinks when crouching or sliding)
	public int entityFlags;  // the engine's entity flag bits (on ground, ducking, ...)
	public long buttons;  // buttons the player holds (Deadlock InputButton bits: 0x1 attack, 0x800 alt fire, 0x2000 reload, 0x200000000 << n ability n+1, ...)
	public int shotSerial;  // serial of the newest Shot

	/** Decode from a little-endian buffer; {@code at} is where this struct starts. */
	public static HeroState read(ByteBuffer b, int at) {
		HeroState v = new HeroState();
		v.seq = b.getInt(at + SEQ_AT);
		v.flags = b.getInt(at + FLAGS_AT);
		v.tick = b.getLong(at + TICK_AT);
		v.serverTime = b.getFloat(at + SERVER_TIME_AT);
		v.heroId = b.getInt(at + HERO_ID_AT);
		v.position = new Vec3(b.getFloat(at + POSITION_AT), b.getFloat(at + POSITION_AT + 4), b.getFloat(at + POSITION_AT + 8));
		v.velocity = new Vec3(b.getFloat(at + VELOCITY_AT), b.getFloat(at + VELOCITY_AT + 4), b.getFloat(at + VELOCITY_AT + 8));
		v.eyePosition = new Vec3(b.getFloat(at + EYE_POSITION_AT), b.getFloat(at + EYE_POSITION_AT + 4), b.getFloat(at + EYE_POSITION_AT + 8));
		v.cameraAngles = new Vec3(b.getFloat(at + CAMERA_ANGLES_AT), b.getFloat(at + CAMERA_ANGLES_AT + 4), b.getFloat(at + CAMERA_ANGLES_AT + 8));
		v.stamina = b.getFloat(at + STAMINA_AT);
		v.staminaMax = b.getFloat(at + STAMINA_MAX_AT);
		v.health = b.getInt(at + HEALTH_AT);
		v.healthMax = b.getInt(at + HEALTH_MAX_AT);
		v.abilityEventSerial = b.getInt(at + ABILITY_EVENT_SERIAL_AT);
		v.recenterSerial = b.getInt(at + RECENTER_SERIAL_AT);
		v.recenterDelta = new Vec3(b.getFloat(at + RECENTER_DELTA_AT), b.getFloat(at + RECENTER_DELTA_AT + 4), b.getFloat(at + RECENTER_DELTA_AT + 8));
		v.hullHeight = b.getFloat(at + HULL_HEIGHT_AT);
		v.entityFlags = b.getInt(at + ENTITY_FLAGS_AT);
		v.buttons = b.getLong(at + BUTTONS_AT);
		v.shotSerial = b.getInt(at + SHOT_SERIAL_AT);
		return v;
	}

	/** Encode into a little-endian buffer; {@code at} is where this struct starts. */
	public void write(ByteBuffer b, int at) {
		b.putInt(at + SEQ_AT, seq);
		b.putInt(at + FLAGS_AT, flags);
		b.putLong(at + TICK_AT, tick);
		b.putFloat(at + SERVER_TIME_AT, serverTime);
		b.putInt(at + HERO_ID_AT, heroId);
		b.putFloat(at + POSITION_AT, position.x()).putFloat(at + POSITION_AT + 4, position.y()).putFloat(at + POSITION_AT + 8, position.z());
		b.putFloat(at + VELOCITY_AT, velocity.x()).putFloat(at + VELOCITY_AT + 4, velocity.y()).putFloat(at + VELOCITY_AT + 8, velocity.z());
		b.putFloat(at + EYE_POSITION_AT, eyePosition.x()).putFloat(at + EYE_POSITION_AT + 4, eyePosition.y()).putFloat(at + EYE_POSITION_AT + 8, eyePosition.z());
		b.putFloat(at + CAMERA_ANGLES_AT, cameraAngles.x()).putFloat(at + CAMERA_ANGLES_AT + 4, cameraAngles.y()).putFloat(at + CAMERA_ANGLES_AT + 8, cameraAngles.z());
		b.putFloat(at + STAMINA_AT, stamina);
		b.putFloat(at + STAMINA_MAX_AT, staminaMax);
		b.putInt(at + HEALTH_AT, health);
		b.putInt(at + HEALTH_MAX_AT, healthMax);
		b.putInt(at + ABILITY_EVENT_SERIAL_AT, abilityEventSerial);
		b.putInt(at + RECENTER_SERIAL_AT, recenterSerial);
		b.putFloat(at + RECENTER_DELTA_AT, recenterDelta.x()).putFloat(at + RECENTER_DELTA_AT + 4, recenterDelta.y()).putFloat(at + RECENTER_DELTA_AT + 8, recenterDelta.z());
		b.putFloat(at + HULL_HEIGHT_AT, hullHeight);
		b.putInt(at + ENTITY_FLAGS_AT, entityFlags);
		b.putLong(at + BUTTONS_AT, buttons);
		b.putInt(at + SHOT_SERIAL_AT, shotSerial);
	}

	@Override
	public boolean equals(Object o) {
		return o instanceof HeroState v
			&& seq == v.seq
			&& flags == v.flags
			&& tick == v.tick
			&& Float.compare(serverTime, v.serverTime) == 0
			&& heroId == v.heroId
			&& position.equals(v.position)
			&& velocity.equals(v.velocity)
			&& eyePosition.equals(v.eyePosition)
			&& cameraAngles.equals(v.cameraAngles)
			&& Float.compare(stamina, v.stamina) == 0
			&& Float.compare(staminaMax, v.staminaMax) == 0
			&& health == v.health
			&& healthMax == v.healthMax
			&& abilityEventSerial == v.abilityEventSerial
			&& recenterSerial == v.recenterSerial
			&& recenterDelta.equals(v.recenterDelta)
			&& Float.compare(hullHeight, v.hullHeight) == 0
			&& entityFlags == v.entityFlags
			&& buttons == v.buttons
			&& shotSerial == v.shotSerial;
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(seq, flags, tick, serverTime, heroId, position, velocity, eyePosition, cameraAngles, stamina, staminaMax, health, healthMax, abilityEventSerial, recenterSerial, recenterDelta, hullHeight, entityFlags, buttons, shotSerial);
	}

	@Override
	public String toString() {
		return "HeroState[" + "seq=" + seq + ", " + "flags=" + flags + ", " + "tick=" + tick + ", " + "serverTime=" + serverTime + ", " + "heroId=" + heroId + ", " + "position=" + position + ", " + "velocity=" + velocity + ", " + "eyePosition=" + eyePosition + ", " + "cameraAngles=" + cameraAngles + ", " + "stamina=" + stamina + ", " + "staminaMax=" + staminaMax + ", " + "health=" + health + ", " + "healthMax=" + healthMax + ", " + "abilityEventSerial=" + abilityEventSerial + ", " + "recenterSerial=" + recenterSerial + ", " + "recenterDelta=" + recenterDelta + ", " + "hullHeight=" + hullHeight + ", " + "entityFlags=" + entityFlags + ", " + "buttons=" + buttons + ", " + "shotSerial=" + shotSerial + "]";
	}
}
