// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Three ints (protocol type ivec3). */
public record Int3(int x, int y, int z) {
	public static final Int3 ZERO = new Int3(0, 0, 0);
}
