// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Bits of a protocol flags field. */
public final class McFlags {
	private McFlags() {}

	public static final int LINKED = 1 << 0;
}
