// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;

/** Minecraft -> Deadlock. Seqlock: seq is odd while the client writes; the seqlock also covers the cube_count entries of Cubes. The client rewrites both only when the set changes (generation bumps). */
public final class McState {
	public static final int OFFSET = 0x1000;
	public static final int SIZE = 0x40;
	public static final int SEQ_AT = 0x0;
	public static final int FLAGS_AT = 0x4;
	public static final int GENERATION_AT = 0x8;
	public static final int CUBE_COUNT_AT = 0xC;
	public static final int BASE_AT = 0x10;
	public static final int FRAME_OFFSET_AT = 0x20;

	public int seq;  // unsigned
	public int flags;  // McFlags
	public int generation;  // bumps whenever the cube set or the offset changes
	public int cubeCount;  // unsigned
	public Int3 base = Int3.ZERO;  // Minecraft block coordinates that cube positions are relative to
	public Double3 frameOffset = Double3.ZERO;  // added to Minecraft block coordinates gives hero-frame blocks: source = to_source(mc + offset)

	/** Decode from a little-endian buffer; {@code at} is where this struct starts. */
	public static McState read(ByteBuffer b, int at) {
		McState v = new McState();
		v.seq = b.getInt(at + SEQ_AT);
		v.flags = b.getInt(at + FLAGS_AT);
		v.generation = b.getInt(at + GENERATION_AT);
		v.cubeCount = b.getInt(at + CUBE_COUNT_AT);
		v.base = new Int3(b.getInt(at + BASE_AT), b.getInt(at + BASE_AT + 4), b.getInt(at + BASE_AT + 8));
		v.frameOffset = new Double3(b.getDouble(at + FRAME_OFFSET_AT), b.getDouble(at + FRAME_OFFSET_AT + 8), b.getDouble(at + FRAME_OFFSET_AT + 16));
		return v;
	}

	/** Encode into a little-endian buffer; {@code at} is where this struct starts. */
	public void write(ByteBuffer b, int at) {
		b.putInt(at + SEQ_AT, seq);
		b.putInt(at + FLAGS_AT, flags);
		b.putInt(at + GENERATION_AT, generation);
		b.putInt(at + CUBE_COUNT_AT, cubeCount);
		b.putInt(at + BASE_AT, base.x()).putInt(at + BASE_AT + 4, base.y()).putInt(at + BASE_AT + 8, base.z());
		b.putDouble(at + FRAME_OFFSET_AT, frameOffset.x()).putDouble(at + FRAME_OFFSET_AT + 8, frameOffset.y()).putDouble(at + FRAME_OFFSET_AT + 16, frameOffset.z());
	}

	@Override
	public boolean equals(Object o) {
		return o instanceof McState v
			&& seq == v.seq
			&& flags == v.flags
			&& generation == v.generation
			&& cubeCount == v.cubeCount
			&& base.equals(v.base)
			&& frameOffset.equals(v.frameOffset);
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(seq, flags, generation, cubeCount, base, frameOffset);
	}

	@Override
	public String toString() {
		return "McState[" + "seq=" + seq + ", " + "flags=" + flags + ", " + "generation=" + generation + ", " + "cubeCount=" + cubeCount + ", " + "base=" + base + ", " + "frameOffset=" + frameOffset + "]";
	}
}
