// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Protocol constants. See protocol/deadcraft-protocol.toml. */
public final class Proto {
	private Proto() {}

	public static final int MAGIC = 0x54464344;
	public static final int VERSION = 3;
	public static final String MAPPING_NAME = "Local\\Deadcraft";
	public static final int MAPPING_SIZE = 262144;
	public static final float UNITS_PER_BLOCK = 64.0f;

	public static final int ABILITY_EVENTS_OFFSET = 0x200;
	public static final int ABILITY_EVENTS_CAPACITY = 32;

	public static final int CUBES_OFFSET = 0x1040;
	public static final int CUBES_CAPACITY = 16384;

	/** Deadlock (Source) units to Minecraft blocks: mc = (x, z, -y) / UNITS_PER_BLOCK. */
	public static Vec3 toMinecraft(Vec3 s) {
		return new Vec3(s.x() / UNITS_PER_BLOCK, s.z() / UNITS_PER_BLOCK, -s.y() / UNITS_PER_BLOCK);
	}

	/** Minecraft blocks to Deadlock (Source) units. */
	public static Vec3 toSource(Vec3 mc) {
		return new Vec3(mc.x() * UNITS_PER_BLOCK, -mc.z() * UNITS_PER_BLOCK, mc.y() * UNITS_PER_BLOCK);
	}
}
