// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;

/** One bullet fired (origin and aim) or one impact (where it hit, and the surface normal). */
public final class Shot {
	public static final int SIZE = 0x30;
	public static final int SERIAL_AT = 0x0;
	public static final int KIND_AT = 0x4;
	public static final int TICK_AT = 0x8;
	public static final int ORIGIN_AT = 0x10;
	public static final int DIRECTION_AT = 0x1C;
	public static final int DAMAGE_AT = 0x28;

	public int serial;  // unsigned
	public int kind;  // ShotKind
	public long tick;  // unsigned
	public Vec3 origin = Vec3.ZERO;  // fired: muzzle; impact: hit point (Source units)
	public Vec3 direction = Vec3.ZERO;  // fired: pitch, yaw, roll in degrees; impact: surface normal
	public int damage;  // impact: damage dealt (0 on world geometry)

	/** Decode from a little-endian buffer; {@code at} is where this struct starts. */
	public static Shot read(ByteBuffer b, int at) {
		Shot v = new Shot();
		v.serial = b.getInt(at + SERIAL_AT);
		v.kind = b.getInt(at + KIND_AT);
		v.tick = b.getLong(at + TICK_AT);
		v.origin = new Vec3(b.getFloat(at + ORIGIN_AT), b.getFloat(at + ORIGIN_AT + 4), b.getFloat(at + ORIGIN_AT + 8));
		v.direction = new Vec3(b.getFloat(at + DIRECTION_AT), b.getFloat(at + DIRECTION_AT + 4), b.getFloat(at + DIRECTION_AT + 8));
		v.damage = b.getInt(at + DAMAGE_AT);
		return v;
	}

	/** Encode into a little-endian buffer; {@code at} is where this struct starts. */
	public void write(ByteBuffer b, int at) {
		b.putInt(at + SERIAL_AT, serial);
		b.putInt(at + KIND_AT, kind);
		b.putLong(at + TICK_AT, tick);
		b.putFloat(at + ORIGIN_AT, origin.x()).putFloat(at + ORIGIN_AT + 4, origin.y()).putFloat(at + ORIGIN_AT + 8, origin.z());
		b.putFloat(at + DIRECTION_AT, direction.x()).putFloat(at + DIRECTION_AT + 4, direction.y()).putFloat(at + DIRECTION_AT + 8, direction.z());
		b.putInt(at + DAMAGE_AT, damage);
	}

	@Override
	public boolean equals(Object o) {
		return o instanceof Shot v
			&& serial == v.serial
			&& kind == v.kind
			&& tick == v.tick
			&& origin.equals(v.origin)
			&& direction.equals(v.direction)
			&& damage == v.damage;
	}

	@Override
	public int hashCode() {
		return java.util.Objects.hash(serial, kind, tick, origin, direction, damage);
	}

	@Override
	public String toString() {
		return "Shot[" + "serial=" + serial + ", " + "kind=" + kind + ", " + "tick=" + tick + ", " + "origin=" + origin + ", " + "direction=" + direction + ", " + "damage=" + damage + "]";
	}
}
