// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Values of a protocol enum field. */
public final class ShotKind {
	private ShotKind() {}

	public static final int FIRED = 1;
	public static final int IMPACT = 2;
	public static final int ABILITY_FIRED = 3;
}
