// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;

/** NUL-padded UTF-8 fixed-size strings. */
final class Utf8 {
	private Utf8() {}

	static String read(ByteBuffer b, int at, int size) {
		int n = 0;
		while (n < size && b.get(at + n) != 0) n++;
		byte[] bytes = new byte[n];
		b.get(at, bytes);
		return new String(bytes, StandardCharsets.UTF_8);
	}

	static void write(ByteBuffer b, int at, int size, String v) {
		byte[] bytes = v.getBytes(StandardCharsets.UTF_8);
		int n = Math.min(bytes.length, size - 1);
		b.put(at, bytes, 0, n);
		for (int i = n; i < size; i++) b.put(at + i, (byte) 0);
	}
}
