// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.
package dev.deadcraft.protocol;

/** Three floats, as the protocol stores them. */
public record Vec3(float x, float y, float z) {
	public static final Vec3 ZERO = new Vec3(0, 0, 0);
}
