// Generated by protocol/generate.py from deadcraft-protocol.toml. Do not edit.

using System.Numerics;
using Deadcraft.Protocol;

namespace Deadcraft.Protocol.Tests;

/// <summary>The values in protocol/golden/v1.values, as code.</summary>
public static class Golden
{
	public const int Extent = 0xA00;

	/// <summary>(absolute offset, struct) for every struct in the fixture.</summary>
	public static readonly (int At, object Value)[] Structs =
	[
		(0x0, new Header { Magic = 1413890884u, Version = 1u, MappingSize = 65536u, UnitsPerBlock = 64.0f, DeadlockPid = 4242u, MinecraftPid = 31337u, DeadlockHeartbeatMs = 123456789012ul, MinecraftHeartbeatMs = 123456789000ul }),
		(0x100, new HeroState { Seq = 42u, Flags = 7u, Tick = 9876543210ul, ServerTime = 154.25f, HeroId = 60u, Position = new Vector3(-1440.0f, 1440.0f, 256.5f), Velocity = new Vector3(305.25f, -33.5f, 0.0f), EyePosition = new Vector3(-1440.0f, 1440.0f, 342.5f), CameraAngles = new Vector3(-35.25f, 35.5f, 0.0f), Stamina = 3.0f, StaminaMax = 4.0f, Health = 756, HealthMax = 822, AbilityEventSerial = 2u }),
		(0x200, new AbilityEvent { Serial = 1u, Kind = 1u, Tick = 9876543000ul, AbilityName = "citadel_ability_dash" }),
		(0x240, new AbilityEvent { Serial = 2u, Kind = 1u, Tick = 9876543100ul, AbilityName = "ability_unicorn_spirit_jet" }),
	];
}
